name: Test and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Check for Fly.io token
        run: |
          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
            echo "❌ FLY_API_TOKEN secret is not set!"
            echo "Please add your Fly.io API token to GitHub repository secrets:"
            echo "1. Go to your repository → Settings → Secrets and variables → Actions"
            echo "2. Click 'New repository secret'"
            echo "3. Name: FLY_API_TOKEN"
            echo "4. Value: [your flyctl auth token]"
            echo "5. Get your token by running: flyctl auth token"
            exit 1
          else
            echo "✅ FLY_API_TOKEN is available"
          fi

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
